# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- none

pr: none
  
name: $(MajorVersion).$(MinorVersion).$(Rev:r).0

pool:
  vmImage: 'windows-latest'

variables:
- name: solution
  value: '**/UniversalFtpServer.sln'
- name: buildPlatform
  value: 'x64'
- name: buildConfiguration
  value: 'Release'
- name: appxPackageDir
  value: '$(build.SourcesDirectory)\DURANGO-FTP\UniversalFtpServer\AppPackages'
- name: build  
  value: '$(Build.BuildId)'
- name: MajorVersion
  value: '3'
- name: MinorVersion
  value: '0'
- group: uwp-pipeline
- name: displayName
  value: 'Retro$(revName) FTP'
- name: identityName
  value: '$(publisherIdentityValue).Retro$(revName)FTP'

steps:

- checkout: none

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    
      #Get source code
      git clone -b main https://github.com/Nun-z/DURANGO-FTP.git --recursive

      #Create certificate
      New-SelfSignedCertificate -Type Custom -Subject $(publisher) -KeyUsage DigitalSignature -FriendlyName "GeneratedCert" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
      $Thumbprint = (Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object {$_.Subject -match '$(publisher)'}).Thumbprint;
      (Get-Content -path ".\DURANGO-FTP\UniversalFtpServer\UniversalFtpServer.csproj" -Raw) -replace '4F63F98559B1B68CF6EEB1A086DFF3B6F059FDA5', $Thumbprint | Set-Content -Path ".\DURANGO-FTP\UniversalFtpServer\UniversalFtpServer.csproj" 

      # Modify store association XML
      [xml]$storeAssociationDoc = Get-Content -Path ".\DURANGO-FTP\UniversalFtpServer\Package.StoreAssociation.xml"
      $storeAssociationDoc.StoreAssociation.Publisher = "$(publisher)"
      $storeAssociationDoc.StoreAssociation.PublisherDisplayName = "$(publisherDisplayName)"
      $storeAssociationDoc.StoreAssociation.ProductReservedInfo.MainPackageIdentityName = "$(identityName)"
      $storeAssociationDoc.StoreAssociation.ProductReservedInfo.ReservedNames.ReservedName = "$(displayName)"
      $storeAssociationDoc.Save(".\DURANGO-FTP\UniversalFtpServer\Package.StoreAssociation.xml")

      # Modify .appxmanifest XML
      [xml]$manifestDoc = Get-Content -Path ".\DURANGO-FTP\UniversalFtpServer\Package.appxmanifest"
      $manifestDoc.Package.Identity.Name = "$(identityName)"
      $manifestDoc.Package.Identity.Publisher = "$(publisher)"
      $manifestDoc.Package.Properties.DisplayName = "$(displayName)"
      $manifestDoc.Package.Properties.PublisherDisplayName = "$(publisherDisplayName)"
      $manifestDoc.Save(".\DURANGO-FTP\UniversalFtpServer\Package.appxmanifest")

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#Auto-increment the build number for store submission      
- task: VersionAPPX@2
  inputs:
    Path: '$(Build.SourcesDirectory)\DURANGO-FTP\UniversalFtpServer'
    VersionNumber: '$(Build.BuildNumber)'
    InjectVersion: True
    OutputVersion: 'OutputedVersion'

#Build the package
- task: VSBuild@1
  inputs:
    platform: '$(buildPlatform)'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
   
#Copy the package to staging directory
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(appxPackageDir)'
    Contents: '**\*.appxupload'
    TargetFolder: '$(build.artifactstagingdirectory)'

#Keep the package instead of deleting it
- task: PublishBuildArtifacts@1
  displayName: 'FTP store'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
