# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- none

pr: none
  
name: $(MajorVersion).$(MinorVersion).$(Rev:r).0

pool:
  vmImage: 'windows-latest'

variables:
- group: uwp-pipeline
- name: solution
  value: '**/RetroArch-msvc2017-UWP.sln'
- name: buildPlatform
  value: 'x64'
- name: buildConfiguration
  value: 'ReleaseANGLE'
- name: appxPackageDir
  value: '$(build.artifactStagingDirectory)\AppxPackages\\'
- name: pfxpath 
  value: '$(build.artifactStagingDirectory)\RetroCert.pfx'
- name: build  
  value: '$(Build.BuildId)'
- name: MajorVersion
  value: '24'
- name: MinorVersion
  value: '6'

steps:
- task: DownloadSecureFile@1
  name: mySecureFile
  displayName: 'Get the pfx file certificate'
  inputs:
    secureFile: '$(signingCert.secureFilePath)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    
      #Import the certificate included in the repo
      Write-Host "Import Certificate" 
      $pfxpath = '$(mySecureFile.secureFilePath)'
      $password = '$(signingCert.password)'
      Add-Type -AssemblyName System.Security
      $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
      $cert.Import($pfxpath, $password, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]"PersistKeySet")
      $store = new-object system.security.cryptography.X509Certificates.X509Store -argumentlist "MY", CurrentUser
      $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]"ReadWrite")
      $store.Add($cert)
      $store.Close()

      #Get RetroArch source code
      git clone -b master https://github.com/Nun-z/RetroArch.git --recursive

      #Add .dll files to build
      git clone https://github.com/Nun-z/RetroArch-Redist.git
    
      #Get .dll files and move them
      Move-Item -Path ".\RetroArch-Redist\other\*.dll" -Destination .\RetroArch\pkg\msvc-uwp\RetroArch-msvc2017-UWP\cores\x64
      Move-Item -Path ".\RetroArch-Redist\cores\*.dll" -Destination .\RetroArch\pkg\msvc-uwp\RetroArch-msvc2017-UWP\cores\x64\cores
      
#Auto-increment the build number for store submission      
- task: VersionAPPX@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    VersionNumber: '$(Build.BuildNumber)'
    InjectVersion: True
    OutputVersion: 'OutputedVersion'

#Build the package
- task: VSBuild@1
  inputs:
    platform: 'x64'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=CI'
   
#Copy the package to staging directory
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '.\RetroArch\pkg\msvc-uwp\x64\ReleaseANGLE\RetroArch-msvc2017-UWP\Upload'
    Contents: '**\*.msixupload'
    TargetFolder: '$(build.artifactstagingdirectory)'

#Keep the package instead of deleting it
- task: PublishBuildArtifacts@1
  displayName: 'RetroRev store'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

#Send to MS Store
#Stable: 9NW7Q07Q6G11
#Unstable: 9NWXWFRL4W11
- task: store-publish@0
  inputs:
    serviceEndpoint: 'MS Store Connection'
    appId: '9NWXWFRL4W11'
    packagePath: '$(build.artifactstagingdirectory)\AppxPackages\RetroArch*.msixupload'
    force: true
    skipPolling: true
    deletePackages: true
    numberOfPackagesToKeep: '0'