# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

steps:

#Duckstation
- task: RunPipelines@2
  inputs:
    serviceConnection: 'PipelineService'
    buildParameters: '[{"SYSTEM.DEBUG":"FALSE"}]'
    project: 'Generate Packages'
    folderPath: '.'
    buildDefinition: 'Duckstation Store Package'
    targetType: 'inline'
    waitForQueuedBuildsToFinish: false
    storeInOutputVariable: false
    customPrefix: '12'
    setBranch: true
    Branch: 'main'

#PPSSPP
- task: RunPipelines@2
  inputs:
    serviceConnection: 'PipelineService'
    project: 'Generate Packages'
    folderPath: '.'
    buildDefinition: 'PPSSPP Store Package'
    targetType: 'inline'
    buildParameters: '[{"SYSTEM.DEBUG":"FALSE"}]'
    waitForQueuedBuildsToFinish: false
    storeInOutputVariable: false
    customPrefix: '12'
    setBranch: true
    Branch: 'main'

#FTP
- task: RunPipelines@2
  inputs:
    serviceConnection: 'PipelineService'
    project: 'Generate Packages'
    folderPath: '.'
    buildDefinition: 'FTP Store Package'
    targetType: 'inline'
    buildParameters: '[{"SYSTEM.DEBUG":"FALSE"}]'
    waitForQueuedBuildsToFinish: false
    storeInOutputVariable: false
    customPrefix: '12'
    setBranch: true
    Branch: 'main'

#RA Stable and RA Unstable
- task: RunPipelines@2
  inputs:
    serviceConnection: 'PipelineService'
    project: 'Generate Packages'
    folderPath: '.'
    buildDefinition: 'RA Store Package Stable'
    targetType: 'inline'
    buildParameters: '[{"SYSTEM.DEBUG":"FALSE"}]'
    waitForQueuedBuildsToFinish: false
    storeInOutputVariable: false
    customPrefix: '12'
    setBranch: true
    Branch: 'main'

#RetroPass
- task: RunPipelines@2
  inputs:
    serviceConnection: 'PipelineService'
    project: 'Generate Packages'
    folderPath: '.'
    buildDefinition: 'RetroPass Package'
    targetType: 'inline'
    buildParameters: '[{"SYSTEM.DEBUG":"FALSE"}]'
    waitForQueuedBuildsToFinish: false
    storeInOutputVariable: false
    customPrefix: '12'
    setBranch: true
    Branch: 'main'
- task: RunPipelines@2
  inputs:
    serviceConnection: 'PipelineService'
    project: 'Generate Packages'
    folderPath: '.'
    buildDefinition: 'Generic Package'
    targetType: 'inline'
    buildParameters: '[{"appxFileName":"SonicCD.appx","Description":"This is an improved version of Sonic CD.  Assets are not included.","lastName":"SonicCD","Screenshot":"Sonic Screenshot.png"},{"appxFileName":"OpenLara.appx","lastName":"OpenLara","Description":"This is an improved version of Tomb Raider.  Assets are not included.","Screenshot":"OpenLara Screenshot.png"},{"appxFileName":"Flycast.appx","lastName":"Dreamcast","Description":"This app emulates the Dreamcast.","Screenshot":"Flycast Screenshot.png"}]'
    #{"appxFileName":"Devilution.appx","lastName":"DevilutionX","Description":"This is a port of Diablo.  Assets are not included.","Screenshot:"DevilutionX Screenshot.png"}]'
    waitForQueuedBuildsToFinish: false
    storeInOutputVariable: false
    customPrefix: "12"
    setBranch: true
    Branch: 'main'
